"""initial

Revision ID: 1732332177
Revises: 
Create Date: 2024-11-23 04:22:57.022104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1732332177'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_action', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('konto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magazyn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produkt', sa.String(length=80), nullable=False),
    sa.Column('cena', sa.Integer(), nullable=False),
    sa.Column('ilosc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('magazyn')
    op.drop_table('konto')
    op.drop_table('historia')
    # ### end Alembic commands ###
