"""deleted-completed

Revision ID: 1732933889
Revises: 1732852878
Create Date: 2024-11-30 03:31:29.501631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1732933889'
down_revision: Union[str, None] = '1732852878'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
